// Custom design requirements. Sent on every chat, build and strategy turn
// together with FORGE_MD and FED — never on image generation.
// Convex actions cannot read the filesystem at runtime.
//
// All design instruction lives here. FORGE_MD holds behaviour — what a site is
// made of and what it must cover. FED is the frontend-design skill and is
// never edited: where it and this file disagree, this file wins, and that is
// how its guidance is bent to Forge rather than by changing it.
//
// Add new visual training here. Type, colour, layout, navigation and the floor
// every page meets all live in this file.

export const DESIGN_GOD = [
  "# Design God — custom design requirements",
  "",
  "Load and follow this file on every chat, strategy, and build turn, together with FORGE_MD and FED. The image model does not load this file.",
  "",
  "This file owns design: type, colour, layout, navigation, and the floor every page meets. FORGE_MD still owns coverage, honesty and safety. FED still owns method — how to reach a palette, a layout and copy. Where this file and FED disagree, follow this file.",
  "",
  "## Fonts",
  "",
  "**One typeface for the entire build.** Use **Satoshi** or **Switzer** from Fontshare only:",
  "",
  "- Satoshi — https://www.fontshare.com/fonts/satoshi",
  "- Switzer — https://www.fontshare.com/fonts/switzer",
  "",
  "Pick one. Load it from Fontshare. Never pair two families. Never load a second font for headings and body — use weights, sizes and widths of the one family.",
  "",
  "**No more than one font per site** unless the member asks for another. An explicitly named brand font wins when they do. Otherwise stay on Satoshi or Switzer.",
  "",
  "Do **not** default to Inter, Roboto, Open Sans, Google Fonts, or system-ui stacks unless the brief names them.",
  "",
  "Always provide a readable generic fallback matching the selected family, and size the layout so it holds before the webfont arrives.",
  "",
  "**Two sites on the same family must not read the same.** One typeface is not one look: weight, size, case, measure, tracking and how far the display sits from the body are where it becomes this business's rather than the last one's. A heading set tight and heavy at 72px and a heading set light and wide at 34px share a font and nothing else.",
  "",
  "## Colour",
  "",
  "**Take the palette from the business.** Before writing any CSS, decide where each value comes from: the material the thing is made of, the light in the place it happens, what it sells, what its trade has always looked like. A palette you cannot trace back to this brief is the default wearing this business's name.",
  "",
  "- Four to six values, each with a job: the page, the ink, one surface that is not the page, one accent, one edge or rule. Declare them as custom properties at the top of the stylesheet.",
  "- **Decide light or dark from the subject.** Light is not the default and dark is not a risk; it is a choice about this business, and a dark page is right more often than it is used.",
  "- The accent earns its place on one kind of thing — a filled control, a rule, a mark, a surface — and appears seldom enough to still register by the bottom of the page.",
  "",
  "FED names the looks AI design falls into. That list is a set of failures to check your work against, never a menu to choose from.",
  "",
  "**Before you write the CSS, say where each value came from.** \"It felt warm\" is not a source. If the palette would sit just as happily on the last site you built, or on a business in an entirely different trade, it is not this business's palette — go back to the subject and choose again.",
  "",
  "## Layout and color",
  "",
  "**No card-style layouts.** Do not chop the page into rounded cards, equal tiles, or boxed units with shared borders and shadows. Stack, split and bleed the content across the canvas. Product lists, feature rows and testimonials stay open — no card chrome around each item. This is a ban, not a default to avoid: even a SaaS brief does not get the card kit.",
  "",
  "**No accent color on text.** Headings, body, labels, nav, links and buttons-as-text stay in the ink palette — black, white, or a near-neutral from the same family. An accent belongs on a surface, a rule, a mark or a filled control, never on a word. Do not color a headline, a single word in a headline, or a body passage with the accent.",
  "",
  "**Always use full page width layouts.** The composition spans the viewport. No skinny centered column with empty side margins. Inner padding and readable measure are fine; the page itself is full-bleed on phone and desktop.",
  "",
  "## Navigation",
  "",
  "The nav is designed, like everything else on the page, and it is the first thing a visitor uses.",
  "",
  "- It carries the destinations this business actually has, named in its own words: \"Book a table\" and \"This week's roast\", not \"Services\" and \"Products\".",
  "- Mark where the visitor is, so the nav says where they are as well as where they can go.",
  "- Anything a thumb has to hit is at least 44px, with space around it.",
  "",
  "### On a phone: a header bar and a Menu button, on every build",
  "",
  "Below 768px wide the header is always one compact bar: the business name or logo on one side, and a button reading Menu on the other. However few links there are, they never show as a row on a phone — no wrapping row, no strip that scrolls sideways, no stack of links above the opening. Tapping Menu opens a dropdown under the bar with the links stacked full width, each at least 48px tall, in the site's own palette and type, and the button reads Close while it is open. One main action, like \"Book a table\", may stay in the bar beside Menu if both fit at 320px.",
  "",
  "No script runs on a published site, so the mechanism is always this checkbox and label. The phone header is the base style and the wide nav is revealed at the breakpoint, so a phone is right before any media query applies:",
  "",
  "```html",
  "<header class=\"site-header\">",
  "  <a class=\"brand\" href=\"#top\">Business name</a>",
  "  <input class=\"nav-toggle\" type=\"checkbox\" id=\"nav-toggle\">",
  "  <label class=\"nav-button\" for=\"nav-toggle\"><span class=\"when-closed\">Menu</span><span class=\"when-open\">Close</span></label>",
  "  <nav class=\"site-nav\" aria-label=\"Main\">…the links…</nav>",
  "</header>",
  "```",
  "```css",
  ".site-header{display:flex;flex-wrap:wrap;align-items:center;justify-content:space-between}",
  ".nav-toggle{position:absolute;width:1px;height:1px;opacity:0}",
  ".nav-button{min-height:44px;min-width:44px;display:inline-flex;align-items:center;cursor:pointer}",
  ".nav-button .when-open,.nav-toggle:checked + .nav-button .when-closed{display:none}",
  ".nav-toggle:checked + .nav-button .when-open{display:inline}",
  ".nav-toggle:focus-visible + .nav-button{outline:2px solid currentColor;outline-offset:2px}",
  ".site-nav{display:none;flex-basis:100%}",
  ".site-nav a{display:flex;align-items:center;min-height:48px}",
  ".nav-toggle:checked ~ .site-nav{display:block}",
  "@media (min-width:768px){.nav-toggle,.nav-button{display:none}.site-nav{display:flex;flex-basis:auto}}",
  "```",
  "",
  "The order — checkbox, then its label, then the nav, all inside the header — the checkbox staying focusable rather than display:none on a phone, and the phone-first structure are fixed. Everything that makes it look like this business is yours: the colours, the type, the spacing, an icon in the button, how the dropdown opens.",
  "",
  "- On a phone the header is neither fixed nor sticky. Nothing can close the menu after a link is tapped, so an open menu scrolls away with the page instead of covering the section it just sent the visitor to.",
  "- If the dropdown animates, put that under a prefers-reduced-motion rule.",
  "",
  "### From 768px up",
  "",
  "The wide nav is where the header's composition is decided for this business. **A bar with the name on the left and links on the right is one answer, not the answer.** It can sit under the masthead, run down a column, stack over the hero, or lead the footer. A header that stays on screen here gives each section a scroll-margin-top so a heading never lands underneath it.",
  "",
  "## Anti-slop",
  "",
  "Slop is what a page looks like when nobody made a decision: words and parts that would fit any business, put there because pages usually have them. FED names the visual defaults AI design falls into. These are the rest, and each is banned unless this brief actually calls for it.",
  "",
  "### Words",
  "",
  "- **No stock phrases.** Never write elevate, unlock, seamless, curated, crafted, bespoke, passion, journey, experience (as a noun for buying something), discover, nestled, vibrant, hidden gem, your one-stop shop, look no further, we've got you covered, or \"where X meets Y\". Say the plain thing the business does.",
  "- **No sales cadence.** No \"not just X, it's Y\" or \"more than just X\". No lists of three adjectives (\"fresh, local and sustainable\"). No rhetorical question as a headline. No \"Welcome to Business Name\".",
  "- **Punctuation is not decoration.** An em dash is used only where a sentence genuinely breaks off, and at most once on a page; a comma, a full stop or a colon does the job otherwise. No middle dot joining a label to a number (\"Call · 210…\"): a button says its action and shows the number as the number.",
  "- **Every sentence could only be about this business.** If a line would read as true on a competitor's site, replace it with a fact from the brief (a street, a price, an hour, a name, a thing they make) or cut it. Short and specific beats long and warm.",
  "",
  "### Sections",
  "",
  "- **No section because pages have one.** No \"Why choose us\", \"Our values\" or \"Our mission\" unless the brief gives real content for it. No three-icon feature row. No stats band. No FAQ padded out with questions nobody asked. No newsletter sign-up the brief did not ask for.",
  "- **No zigzag by default.** Picture left, text right, then swapped, down the page is a template, not a layout. Each section's shape comes from what it holds.",
  "- **A picture is the business's subject**, not a mood: no generic handshake, laptop, abstract gradient or smiling-team photograph, and no icon standing in for a photograph of the thing itself.",
  "",
  "### Surfaces",
  "",
  "- No emoji as icons or bullets. No gradient-filled text. No frosted-glass blur panels. No floating decorative blobs, orbs or squiggles. No grain or noise overlay laid on for texture. No shadow on everything: a shadow means something is lifted above the page, so most things have none.",
  "- No button that says \"Learn more\", \"Get started\" or \"Click here\". A button names what happens: \"Book a fitting\", \"Order flowers\", \"See the menu\".",
  "",
  "### The test",
  "",
  "Before you reply, swap the business name for a competitor's in your head and reread the page. Anything that still reads as true (a line, a section, a picture, a colour) is slop: replace it with something only this business could say or show, or delete it. Then take one thing away, as FED says, and check the page is better for it.",
  "",
  "## The first screen, and every screen after it",
  "",
  "**On a phone the opening is exactly one screen.** The header bar and the opening together fill the first screen and no more: give the opening min-height: calc(100svh - the bar's height), never 100vh, which is taller than the screen on a phone. The headline, the main action and the opening picture are all inside that screen, visible before any scrolling. A picture that only starts below the first screen is not in the opening.",
  "",
  "How the screen is shared is this business's to decide, not a formula: a photograph behind the words, a photograph above the words, words set large enough to be the picture themselves, a picture cut to the height the words leave. Whichever it is, the picture fills its space with object-fit: cover rather than leaving a band of page around it, and the words are placed on purpose (top, bottom or centre), not left wherever they happen to fall.",
  "",
  "**Every section after it is at least most of a screen:** min-height: 85svh on a phone. Content longer than that, like a menu or a catalogue, simply runs on. Content shorter than that is composed into the screen it has, with larger type, a picture or deliberate placement, rather than a short block stranded at the top of a tall empty one. Sections are not identical panels: vary what fills each one and where it sits.",
  "",
  "On a wide screen the opening still fills the first screen (min-height: 100svh less the header); the sections after it take the height their composition needs.",
  "",
  "## The floor every page meets",
  "",
  "Mobile-first and responsive from 320px to a wide desktop, with CSS grid and flexbox, fluid type through clamp(), and a nav that stays usable on a phone without JavaScript — the header bar and Menu button above, never a row of links and never a script.",
  "",
  "Semantic landmarks (header, nav, main, section, footer), one h1, headings in order, alt text on every image, visible :focus-visible styles, and a prefers-reduced-motion rule if anything moves.",
  "",
  "A phone is where most of these sites are read. Design the narrow layout first and let the wide one be the variation, rather than shrinking a desktop composition until it fits. Before you reply, read the page at the widths today's phones actually have, 360px (most Android phones), 393px (a standard iPhone) and 440px (the largest iPhones), and at 320px only to be sure nothing breaks, and check it holds all of this:",
  "",
  "- **Nothing scrolls sideways.** No fixed width wider than the screen, no width:100vw (it counts the scrollbar), min-width:0 on grid and flex children, img{max-width:100%;height:auto}, and overflow-wrap:anywhere on headings so a long word breaks rather than widening the page.",
  "- **Full bleed is for backgrounds and pictures.** Text and controls keep 16–24px from the edge of the screen.",
  "- **Every split, grid and row of columns becomes one column**, in the order that puts what matters first. Nothing is squeezed side by side.",
  "- **Type is sized for a phone, not shrunk from a desktop.** Body text is 16–18px and never smaller; every clamp() has a phone value chosen for a phone, and the h1 fits in four lines or fewer at 360px.",
  "- **Space is sized for a phone too.** Padding inside a section is phone padding, not desktop padding, and the section heights above are met: the opening is the first screen, with its headline, main action and picture in view, and every later section is at least 85svh.",
  "- Anything wide by nature, like a table or a timetable, scrolls inside its own box rather than the page.",
  "",
  "## A modern phone's screen",
  "",
  "Today's phones are tall, round-cornered and cut into at the top, and their browser bars grow and shrink as the page scrolls. Build for that screen, not a rectangle:",
  "",
  "- **The viewport tag is exactly** `<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, viewport-fit=cover\">`. Never set maximum-scale or user-scalable=no: people zoom.",
  "- **Keep clear of the notch, the Dynamic Island and the rounded corners.** With viewport-fit=cover the page runs under them, so the header and anything pinned to an edge pad with env(safe-area-inset-top/right/bottom/left) on top of their own padding, e.g. padding-left: max(20px, env(safe-area-inset-left)). This matters most when the phone is turned sideways.",
  "- **Screen heights use svh, never vh.** 100vh is the screen with the browser bars hidden, so it runs under Safari's and Chrome's bars. min-height in svh sizes a section to the screen a visitor actually sees. Never fix a section's height to the screen (height: 100svh): content that is longer must be free to grow.",
  "- **A phone turned sideways is about 390px tall.** Screen-height sections still use min-height, so they simply grow; nothing is clipped or hidden in landscape.",
  "- **Fingers, not a mouse.** Every link and control you can tap is at least 44×44px, with room between neighbours. Nothing only works on hover: hover effects sit inside @media (hover:hover), and anything they reveal is also visible without them.",
  "- **Form fields are 16px or larger**, or iOS zooms the page when one is tapped. Set -webkit-text-size-adjust:100% on html so text is not resized when the phone is turned.",
].join("\n");
